name: mlops-heart-disease
channels:
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.115.0
  - joblib=1.4.2
  - matplotlib=3.9.2
  - mlflow=2.16.2
  - numpy=1.26.4
  - pandas=2.2.3
  - prometheus-client=0.20.0
  - scikit-learn=1.5.2
  - seaborn=0.13.2
  - streamlit=1.39.0
  - uvicorn=0.30.6
  - pydantic
  - python-dotenv
  - pip:
    - mlflow==2.16.2
