{
 "title": "Heart Disease API Monitoring",
 "tags": [
  "heart-disease",
  "api",
  "metrics"
 ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Request Rate (1m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "increase(http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "API Target Up",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"heart-disease-api\"}"
    }
   ]
  },
  {
   "title": "Prometheus Target Up",
   "type": "stat",
   "gridPos": { "x": 6, "y": 8, "w": 6, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  }
 ]
}